# docker-compose.yaml
version: '3.7'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/,
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root1234
      MINIO_ROOT_PASSWORD: root1234
    volumes:
      - minio-storage:/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
  firebase:
    image: spine3/firebase-emulator:latest
    container_name: firebase
    restart: always
    ports:
      - "8080:8080"
      - "4000:4000"
      - "9005:9005"
    environment:
      - GCP_PROJECT=bazalt-89939
      - RDB_EMULATOR_PORT=9005
  server:
    build:
      context: https://github.com/Nihuaway/Bazalt#
      dockerfile: Dockerfile
    ports:
      - 8000:80
    image: https://github.com/Nihuaway/Bazalt.git/
    container_name: server
    env_file:
      - .env
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  minio-storage:
  node_modules:
