# docker-compose.yaml
version: '3.7'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/,
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root1234
      MINIO_ROOT_PASSWORD: root1234
    volumes:
      - minio-storage:/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
  firebase:
    image: spine3/firebase-emulator:latest
    container_name: firebase
    restart: always
    ports:
      - "8080:8080"
      - "4000:4000"
      - "9005:9005"
    environment:
      - GCP_PROJECT=bazalt
      - RDB_EMULATOR_PORT=9005
  backend:
    # build: https://github.com/Nihuaway/Bazalt.git#master:backend
    build: /backend
    ports:
      - 8000:8000
    image: backend
    container_name: backend
    volumes:
      - .:/home/node/app
      - backend:/home/node/app/node_modules
  frontend:
    # build: https://github.com/Nihuaway/Bazalt.git#master:frontend
    build: /frontend
    ports:
      - 3000:3000
    image: frontend
    container_name: frontend
    volumes:
      - .:/home/node/app/
      - frontend:/home/node/app/node_modules

volumes:
  minio-storage:
  backend:
  frontend:
